### ISSUE TITLE
Randomizer configuration - Configurator Does Not Create File When Ammo Mode is Selected

### ISSUE THREAD

**Issue by NeoSyther** [HansRandomizer/Resident-Evil-0-Randomizer#1]
![Screenshot 2023-07-30 033506](https://github.com/HansRandomizer/Resident-Evil-0-Randomizer/assets/140940758/ffe94b06-840c-49c9-b561-4df4790b8f2c)

When trying to generate a configuration file with the (Mode: More Ammo) it will not bring up the prompt to save the file.

**Comment by HansRandomizer** [comment]
Hi,

could you please start the config tool and open the "Dev Tools"? You can use the shortcut "Ctrl+Shift+I" or the F12 key.

Then look out for a tab called "Console", click on it. There will be some debug output showing up. 

Enter your seed and klick the "Generate Config" button again. Please copy the output of the console and paste it here.


PS: What's your OS and system language, system local?

**Comment by NeoSyther** [comment]
Windows 11 Home
![Screenshot 2023-07-30 064717](https://github.com/HansRandomizer/Resident-Evil-0-Randomizer/assets/140940758/6e8ade2b-3fe1-434f-acd0-4ef373d0e914)

**Comment by HansRandomizer** [comment]
I figured out the cause of the error. This happens, when **"More Ammo"-mode** is selected.. 

I'll be working on a fix soon. In the meantime, you can try any of the other modes. 

Thank you for reporting!

**Comment by HansRandomizer** [comment]
@NeoSyther 
I created a fix , could you try it out? https://github.com/HansRandomizer/Resident-Evil-0-Randomizer/releases/tag/1.0.1

**Comment by NeoSyther** [comment]
It works now. Sorry about the late reply. 

![Screenshot 2023-07-31 003913](https://github.com/HansRandomizer/Resident-Evil-0-Randomizer/assets/140940758/b90237bc-db14-4083-9988-19c4009309ab)
