### ISSUE TITLE
The configurator doesn't start

### ISSUE THREAD

**Issue by nicolascarre** [HansRandomizer/Resident-Evil-0-Randomizer#7]
I tried with all your release, but when I start the configurator nothing happened.
I can see some process appear in the task manager, then disappear instantly.
Tried to run as admin, same result.

Tried on Windows 8.1

**Comment by HansRandomizer** [comment]
Hi,

the configurator is based on electron.js which, unfortunately, stopped supporting Windows 8.1. 

Unfortunately the only way to make it work is either upgrading to Win 10 or use a vm. There are free trial versions  of Win 10 vms here: https://www.microsoft.com/en-us/evalcenter/evaluate-windows-10-enterprise
. 

Best Regards,

Hans
